import pandas as pd
from datetime import datetime

def process_qc_submission(user, task_type, confidence, data_path="task_data.csv"):
    """Logs a QC submission with autogenerated TaskID."""
    try:
        df = pd.read_csv(data_path)
    except FileNotFoundError:
        df = pd.DataFrame(columns=["UserID", "TaskID", "TaskType", "SubmissionTime", "QC_Passed", "QC_Total"])

    next_id = f"TASK{len(df) + 1:03d}"
    new_task = {
        "UserID": user,
        "TaskID": next_id,
        "TaskType": task_type,
        "SubmissionTime": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "QC_Passed": round(confidence, 2),
        "QC_Total": 100
    }

    df = pd.concat([df, pd.DataFrame([new_task])], ignore_index=True)
    df.to_csv(data_path, index=False)
    return new_task